// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: transaction.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions(
from_user_id,
to_user_id,
amount
) VALUES (
    $1, $2, $3
) RETURNING id, from_user_id, to_user_id, amount, created_at, updated_at, deleted_at, is_deleted
`

type CreateTransactionParams struct {
	FromUserID uuid.UUID      `json:"from_user_id"`
	ToUserID   uuid.UUID      `json:"to_user_id"`
	Amount     pgtype.Numeric `json:"amount"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction, arg.FromUserID, arg.ToUserID, arg.Amount)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.FromUserID,
		&i.ToUserID,
		&i.Amount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsDeleted,
	)
	return i, err
}
