global:
  evaluation_interval: 30s
  scrape_interval: 5s
scrape_configs:
  - job_name: 'appcollector'
    static_configs:
      - targets: ['grey-app-otel-collector:9565']
  - job_name: 'collectorinstance'
    static_configs:
      - targets: ['host.docker.internal:8888']